import { createContext, useContext, useState, ReactNode } from 'react';

// 定义支持的语言类型
type Language = 'zh' | 'en';

// 定义语言上下文类型
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

// 创建语言上下文
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译字典
const translations = {
  zh: {
    '首页': '首页',
    '文物': '文物',
    '对话': '对话',
    '游戏': '游戏',
    '跨越千年的对话': '跨越千年的对话',
    'AI 生成内容仅供参考，请以官方历史记载为准': 'AI 生成内容仅供参考，请以官方历史记载为准',
    '向{{name}}提问...': '向{{name}}提问...',
    '灵识觉醒中': '灵识觉醒中',
    '3D模型展示': '3D模型展示',
    '加载中...': '加载中...',
    '3D模型加载失败': '3D模型加载失败',
    '显示默认模型': '显示默认模型',
    '猜文物': '猜文物',
    '拼图游戏': '拼图游戏',
    '开始游戏': '开始游戏',
    '重新开始': '重新开始',
    '提示': '提示',
    '恭喜你猜对了！': '恭喜你猜对了！',
    '再接再厉！': '再接再厉！',
    '查看文物详情': '查看文物详情',
    '文物详情': '文物详情',
    '返回': '返回',
    '历史背景': '历史背景',
    '文物特点': '文物特点',
    '保存状态': '保存状态',
    '苏州博物馆': '苏州博物馆',
    '贝聿铭的建筑杰作 · 吴文化的殿堂': '贝聿铭的建筑杰作 · 吴文化的殿堂',
    '关于博物馆': '关于博物馆',
    '苏州博物馆成立于1960年，位于苏州古城东北街。2006年10月，由世界著名建筑大师贝聿铭设计的苏州博物馆新馆建成开放。新馆建筑融传统与现代于一体，与周边的拙政园、狮子林等古典园林相得益彰，成为"中而新、苏而新"的建筑典范。': '苏州博物馆成立于1960年，位于苏州古城东北街。2006年10月，由世界著名建筑大师贝聿铭设计的苏州博物馆新馆建成开放。新馆建筑融传统与现代于一体，与周边的拙政园、狮子林等古典园林相得益彰，成为"中而新、苏而新"的建筑典范。',
    '博物馆以吴地历史、吴塔国宝、吴中风雅、吴门书画四大系列为主要陈列内容，馆藏文物4万余件，其中国家一级文物近百件，精品荟萃，充分展示了苏州悠久灿烂的历史文化。': '博物馆以吴地历史、吴塔国宝、吴中风雅、吴门书画四大系列为主要陈列内容，馆藏文物4万余件，其中国家一级文物近百件，精品荟萃，充分展示了苏州悠久灿烂的历史文化。',
    '贝聿铭先生曾说："苏州博物馆的设计是我在中国最后一个作品，也是我心中最爱的作品。"这座将苏州古典园林的空间意境与现代建筑完美结合的博物馆，已成为苏州的文化新地标。': '贝聿铭先生曾说："苏州博物馆的设计是我在中国最后一个作品，也是我心中最爱的作品。"这座将苏州古典园林的空间意境与现代建筑完美结合的博物馆，已成为苏州的文化新地标。',
    '参观信息': '参观信息',
    '开放时间': '开放时间',
    '周二至周日 9:00-17:00（16:00停止入馆）': '周二至周日 9:00-17:00（16:00停止入馆）',
    '周一闭馆（国家法定节假日除外）': '周一闭馆（国家法定节假日除外）',
    '地址': '地址',
    '江苏省苏州市姑苏区东北街204号': '江苏省苏州市姑苏区东北街204号',
    '（紧邻拙政园、狮子林）': '（紧邻拙政园、狮子林）',
    '咨询电话': '咨询电话',
    '0512-67575666': '0512-67575666',
    '快速入口': '快速入口',
    '功能页': '功能页',
    '我的': '我的',
    '我的面板': '我的面板',
    '这里是你的个人主页，快速进入常用功能和收藏。': '这里是你的个人主页，快速进入常用功能和收藏。',
    '欢迎回来，游客': '欢迎回来，游客',
    '游客': '游客',
    '你的功能入口已在下方准备好。': '你的功能入口已在下方准备好。',
    '我的收藏': '我的收藏',
    '我的功能': '我的功能',
    '设置': '设置',
    '清除足迹': '清除足迹',
    '收藏': '收藏',
    '已收藏': '已收藏',
    '最近浏览': '最近浏览',
    '条记录': '条记录',
    '在这里进入 AI 对话、拼图游戏和猜文物等功能': '在这里进入 AI 对话、拼图游戏和猜文物等功能',
    '进入': '进入',
    '你还没有收藏过文物': '你还没有收藏过文物',
    '你还没有浏览过文物': '你还没有浏览过文物',
    '已记录你的最近浏览历史，点击“探索足迹”查看详细内容。': '已记录你的最近浏览历史，点击“探索足迹”查看详细内容。',
    '探索足迹页面会记录你查看的每一个文物': '探索足迹页面会记录你查看的每一个文物',
    '退出收藏': '退出收藏',
    '精品文物': '精品文物',
    'AI对话': 'AI对话',
    '与文物互动': '与文物互动',
    '互动游戏': '互动游戏',
    '趣味学习吴文化': '趣味学习吴文化',
    'The Aesthetic': '美学',
    'Exploration': '探索',
    'Collection': '馆藏',
    'Intelligence': '智能',
    'Interactive': '互动',
    'Suzhou Museum Art Collection': '苏州博物馆艺术馆藏',
    '开启探索之旅': '开启探索之旅',
    '沉浸式阅览馆藏珍品': '沉浸式阅览馆藏珍品',
    '进入库房': '进入库房',
    '与跨越千年的文物对谈': '与跨越千年的文物对谈',
    '即刻启程': '即刻启程',
    '趣味探寻吴地文明': '趣味探寻吴地文明',
    '共收录 {count} 件珍贵文物': '共收录 {count} 件珍贵文物',
    '在游戏中学习吴文化知识': '在游戏中学习吴文化知识',
    '文物拼图': '文物拼图',
    '将打乱的文物图片拼回完整': '将打乱的文物图片拼回完整',
    '猜猜文物': '猜猜文物',
    '根据线索猜测文物名称': '根据线索猜测文物名称',
    '💡 提示：通过游戏可以更好地记住文物的特征和历史背景哦！': '💡 提示：通过游戏可以更好地记住文物的特征和历史背景哦！',
    '文物不存在': '文物不存在',
    '返回文物列表': '返回文物列表',
    '与TA对话': '与TA对话',
    '📷 图片': '📷 图片',
    '3D': '3D',
    '朝代': '朝代',
    '年代': '年代',
    '文物介绍': '文物介绍',
    '文物自述': '文物自述',
    '得分: ': '得分: ',
    ' / ': ' / ',
    '这是什么文物？': '这是什么文物？',
    '🔍 显示线索 (3次)': '🔍 显示线索 (3次)',
    '🔍 再清晰一点 (2次)': '🔍 再清晰一点 (2次)',
    '🔍 最后一次提示 (1次)': '🔍 最后一次提示 (1次)',
    '✓ 已显示完整图片': '✓ 已显示完整图片',
    '💡 朝代：': '💡 朝代：',
    '💡 年代：': '💡 年代：',
    '💡 提示：': '💡 提示：',
    '🎉 回答正确！': '🎉 回答正确！',
    '❌ 正确答案是：': '❌ 正确答案是：',
    '游戏结束！': '游戏结束！',
    '完美！你是文物专家！': '完美！你是文物专家！',
    '不错！继续加油！': '不错！继续加油！',
    '多看看文物介绍吧~': '多看看文物介绍吧~',
    '文物修复计划': '文物修复计划',
    'Puzzle Challenge': 'Puzzle Challenge',
    '正在修复': '正在修复',
    '移动步数': '移动步数',
    '隐藏原图': '隐藏原图',
    '查看原图': '查看原图',
    '修复成功！': '修复成功！',
    '你只用了 {moves} 步就让 {artifactName} 焕发新生。': '你只用了 {moves} 步就让 {artifactName} 焕发新生。',
    '你只用了 {moves} 次交换就让 {artifactName} 焕发新生。': '你只用了 {moves} 次交换就让 {artifactName} 焕发新生。',
    '再玩一次': '再玩一次',
    '挑战下一关': '挑战下一关',
    '回到大厅': '回到大厅',
    '欢迎语前缀': '(整理了一下衣角) 游客你好，我是',
    '欢迎语中缀1': '。在这博物馆的橱窗里待久了，甚是寂寞。你是想听听',
    '欢迎语中缀2': '的故事，还是想了解我的来历？',
    '真珠舍利宝幢': '真珠舍利宝幢',
    '北宋': '北宋',
    '公元960-1127年': '公元960-1127年',
    '苏州博物馆镇馆之宝，是北宋时期的佛教圣物。宝幢通高122.6厘米，由木胎、金银、珍珠、宝石等材料制成，工艺精湛，是中国佛教文物中的珍品。': '苏州博物馆镇馆之宝，是北宋时期的佛教圣物。宝幢通高122.6厘米，由木胎、金银、珍珠、宝石等材料制成，工艺精湛，是中国佛教文物中的珍品。',
    '我诞生于北宋太平兴国二年，是当时吴越国王钱俶为祈求国泰民安而建造的。历经千年风霜，我见证了苏州的兴衰变迁，承载着虔诚的信仰和精湛的工艺。每一颗珍珠、每一片金叶，都凝聚着古人的智慧与虔诚。': '我诞生于北宋太平兴国二年，是当时吴越国王钱俶为祈求国泰民安而建造的。历经千年风霜，我见证了苏州的兴衰变迁，承载着虔诚的信仰和精湛的工艺。每一颗珍珠、每一片金叶，都凝聚着古人的智慧与虔诚。',
    '秘色瓷莲花碗': '秘色瓷莲花碗',
    '五代': '五代',
    '公元907-960年': '公元907-960年',
    '秘色瓷是越窑青瓷中的极品，专供皇室使用。这件莲花碗釉色青翠，造型优美，代表了五代时期制瓷工艺的最高水平。': '秘色瓷是越窑青瓷中的极品，专供皇室使用。这件莲花碗釉色青翠，造型优美，代表了五代时期制瓷工艺的最高水平。',
    '我来自越窑，那个出产\'秘色瓷\'的神秘之地。我的釉色如千峰翠色，如湖水碧波。在五代十国的乱世中，我曾是王室贵胄的珍宝。如今静卧于苏州博物馆，继续诉说着千年前的繁华。': '我来自越窑，那个出产\'秘色瓷\'的神秘之地。我的釉色如千峰翠色，如湖水碧波。在五代十国的乱世中，我曾是王室贵胄的珍宝。如今静卧于苏州博物馆，继续诉说着千年前的繁华。',
    '吴王夫差剑': '吴王夫差剑',
    '春秋': '春秋',
    '公元前473年': '公元前473年',
    '吴王夫差剑是春秋时期吴国的青铜兵器，剑身修长，剑刃锋利，剑格镶嵌绿松石，剑身有清晰的铭文\'攻吴王夫差自作其元用\'。此剑代表了春秋时期吴越地区青铜铸造工艺的最高水平，是研究吴越历史和青铜文化的珍贵实物资料。': '吴王夫差剑是春秋时期吴国的青铜兵器，剑身修长，剑刃锋利，剑格镶嵌绿松石，剑身有清晰的铭文\'攻吴王夫差自作其元用\'。此剑代表了春秋时期吴越地区青铜铸造工艺的最高水平，是研究吴越历史和青铜文化的珍贵实物资料。',
    '我是吴王夫差的佩剑，见证了春秋末年吴越争霸的风云岁月。当年夫差持我南征北战，称霸一时。我曾饮过无数勇士的鲜血，也曾见证过吴越两国的兴衰荣辱。千年之后，我依然锋利如初，仿佛还能感受到当年金戈铁马的气息。': '我是吴王夫差的佩剑，见证了春秋末年吴越争霸的风云岁月。当年夫差持我南征北战，称霸一时。我曾饮过无数勇士的鲜血，也曾见证过吴越两国的兴衰荣辱。千年之后，我依然锋利如初，仿佛还能感受到当年金戈铁马的气息。',
    '蟠螭三足提梁盉': '蟠螭三足提梁盉',
    '战国': '战国',
    '公元前475-221年': '公元前475-221年',
    '蟠螭三足提梁盉是战国时期的青铜酒器，造型独特，器身装饰蟠螭纹，三足鼎立，提梁设计精巧。此器铸造工艺精湛，纹饰繁复精美，是战国时期青铜艺术的杰出代表，反映了当时高超的青铜铸造技术和审美水平。': '蟠螭三足提梁盉是战国时期的青铜酒器，造型独特，器身装饰蟠螭纹，三足鼎立，提梁设计精巧。此器铸造工艺精湛，纹饰繁复精美，是战国时期青铜艺术的杰出代表，反映了当时高超的青铜铸造技术和审美水平。',
    '我是战国时期的青铜酒器，见证了那个百家争鸣、英雄辈出的时代。我的身上布满了精美的蟠螭纹饰，每一处都凝聚着工匠的心血。在战国的宴会上，我曾盛放过香醇的美酒，见证过无数次觥筹交错的场景。岁月流转，我依然保持着当年的威严与华美。': '我是战国时期的青铜酒器，见证了那个百家争鸣、英雄辈出的时代。我的身上布满了精美的蟠螭纹饰，每一处都凝聚着工匠的心血。在战国的宴会上，我曾盛放过香醇的美酒，见证过无数次觥筹交错的场景。岁月流转，我依然保持着当年的威严与华美。',
    '随机推荐': '随机推荐',
    '换一批': '换一批',
    '搜索文物...': '搜索文物...',
    'FEATURED ARCHIVE': '精选馆藏',
    'Dynasty': '朝代',
    'EXQUISITE ARTIFACTS': '精品文物',
    'SUZHOU MUSEUM DIGITAL COLLECTION': '苏州博物馆数字馆藏',
    'EXPLORE STORY': '探索故事',
    'View original': '查看原图',
    '更多馆藏': '更多馆藏',
    'Restoring': '正在修复',
    'Moves': '移动步数',
    '交换次数': '交换次数',
    '点击两个格子交换位置，将图片恢复原样': '点击两个格子交换位置，将图片恢复原样',
    'Show clue (3 times)': '显示线索 (3次)',
    'A bit clearer (2 times)': '再清晰一点 (2次)',
    'Final hint (1 time)': '最后一次提示 (1次)',
    'Full image displayed': '已显示完整图片',
    'My Favorites': '我的收藏',
    'Exploration Footprints': '探索足迹',
    'Log Out': '退出登录',
    'DIGITAL PASS: SM-0824': '数字通行证: SM-0824',
    'My Achievements': '我的成就',
    '已解锁': '已解锁',
    '万物皆观': '万物皆观',
    '已浏览全部文物': '已浏览全部文物',
  },
  en: {
    '首页': 'Home',
    '文物': 'Artifacts',
    '对话': 'Chat',
    '游戏': 'Games',
    '跨越千年的对话': 'Cross-millennium Dialogue',
    'AI 生成内容仅供参考，请以官方历史记载为准': 'AI-generated content is for reference only, please refer to official historical records',
    '向{{name}}提问...': 'Ask {{name}}...',
    '灵识觉醒中': 'Spirit Awakening',
    '3D模型展示': '3D Model Display',
    '加载中...': 'Loading...',
    '3D模型加载失败': '3D model loading failed',
    '显示默认模型': 'Show default model',
    '猜文物': 'Guess Artifact',
    '拼图游戏': 'Puzzle Game',
    '开始游戏': 'Start Game',
    '重新开始': 'Restart',
    '提示': 'Hint',
    '恭喜你猜对了！': 'Congratulations, you guessed it right!',
    '再接再厉！': 'Keep it up!',
    '查看文物详情': 'View Artifact Details',
    '文物详情': 'Artifact Details',
    '返回': 'Back',
    '历史背景': 'Historical Background',
    '文物特点': 'Artifact Features',
    '保存状态': 'Save State',
    '苏州博物馆': 'Suzhou Museum',
    '贝聿铭的建筑杰作 · 吴文化的殿堂': 'I.M. Pei\'s Architectural Masterpiece · Palace of Wu Culture',
    '关于博物馆': 'About the Museum',
    '苏州博物馆成立于1960年，位于苏州古城东北街。2006年10月，由世界著名建筑大师贝聿铭设计的苏州博物馆新馆建成开放。新馆建筑融传统与现代于一体，与周边的拙政园、狮子林等古典园林相得益彰，成为"中而新、苏而新"的建筑典范。': 'Suzhou Museum was founded in 1960 and is located on Dongbei Street in the ancient city of Suzhou. In October 2006, the new Suzhou Museum designed by world-renowned architect I.M. Pei was completed and opened. The new museum building integrates tradition and modernity, complementing the surrounding classical gardens such as the Humble Administrator\'s Garden and Lion Grove, becoming an architectural model of "Chinese yet new, Suzhou yet new".',
    '博物馆以吴地历史、吴塔国宝、吴中风雅、吴门书画四大系列为主要陈列内容，馆藏文物4万余件，其中国家一级文物近百件，精品荟萃，充分展示了苏州悠久灿烂的历史文化。': 'The museum\'s main exhibitions are divided into four series: Wu region history, Wu tower national treasures, Wu style elegance, and Wu school calligraphy and painting. It houses over 40,000 cultural relics, including nearly 100 national first-class cultural relics, showcasing Suzhou\'s long and splendid historical culture.',
    '贝聿铭先生曾说："苏州博物馆的设计是我在中国最后一个作品，也是我心中最爱的作品。"这座将苏州古典园林的空间意境与现代建筑完美结合的博物馆，已成为苏州的文化新地标。': 'Mr. I.M. Pei once said: "The design of Suzhou Museum is my last work in China and my favorite work in my heart." This museum, which perfectly combines the spatial artistic conception of Suzhou classical gardens with modern architecture, has become a new cultural landmark of Suzhou.',
    '参观信息': 'Visitor Information',
    '开放时间': 'Opening Hours',
    '周二至周日 9:00-17:00（16:00停止入馆）': 'Tuesday to Sunday 9:00-17:00 (last entry at 16:00)',
    '周一闭馆（国家法定节假日除外）': 'Closed on Mondays (except national statutory holidays)',
    '地址': 'Address',
    '江苏省苏州市姑苏区东北街204号': '204 Dongbei Street, Gusu District, Suzhou, Jiangsu Province',
    '（紧邻拙政园、狮子林）': '(Adjacent to Humble Administrator\'s Garden and Lion Grove)',
    '咨询电话': 'Inquiry Phone',
    '0512-67575666': '0512-67575666',
    '快速入口': 'Quick Access',
    '功能页': 'Functions',
    '我的': 'My',
    '我的面板': 'My Panel',
    '这里是你的个人主页，快速进入常用功能和收藏。': 'This is your personal page, with quick access to features and favorites.',
    '欢迎回来，游客': 'Welcome back, guest',
    '游客': 'Guest',
    '你的功能入口已在下方准备好。': 'Your function shortcuts are ready below.',
    '我的收藏': 'My Favorites',
    '我的功能': 'My Features',
    '设置': 'Settings',
    '清除足迹': 'Clear Footprints',
    '收藏': 'Favorite',
    '已收藏': 'Collected',
    '最近浏览': 'Recent Browsing',
    '条记录': 'records',
    '在这里进入 AI 对话、拼图游戏和猜文物等功能': 'Access AI Chat, Puzzle, and Guess features here',
    '进入': 'Enter',
    '你还没有收藏过文物': 'You have not favorited any artifacts yet',
    '你还没有浏览过文物': 'You have not viewed any artifacts yet',
    '已记录你的最近浏览历史，点击“探索足迹”查看详细内容。': 'Your recent browsing history is recorded. Click "Exploration Footprints" to view the details.',
    '探索足迹页面会记录你查看的每一个文物': 'The footprints page records every artifact you have viewed.',
    '退出收藏': 'Exit Favorites',
    '我的成就': 'My Achievements',
    '未登录': 'Not Logged In',
    '登录后开启你的数字博物馆之旅，记录每一次跨越时空的相遇': 'Log in to start your digital museum journey and record every time-travel encounter.',
    '即刻登录': 'Log in now',
    '退出登录': 'Log Out',
    '登录': 'Log In',
    '注册': 'Register',
    '邮箱地址': 'Email Address',
    '输入密码': 'Enter Password',
    '创建账号': 'Create Account',
    '点击即代表同意《数字苏博服务协议》': 'By clicking, you agree to the Digital Suzhou Museum Terms of Service.',
    '探索足迹': 'Exploration Footprints',
    '数字发现': 'Digital Discovery',
    '灵识对话': 'Spirit Dialogue',
    '文物修复': 'Artifact Restoration',
    '博学鉴宝': 'Scholar\'s Riddle',
    '跨越千年岁月，与馆藏珍宝席地而谈。听听那件秘色瓷或古砚台，都有什么想对你说的。': 'Cross millennia to sit down with museum treasures. Hear what the secret-color porcelain or ancient inkstone wants to tell you.',
    '指尖触碰，将破碎的历史记忆拼凑完整。': 'Touch with your fingertips to piece together shattered memories of history.',
    '凭一丝线索，识万千珍玩。你能认出它吗？': 'With a single clue, recognize thousands of treasures. Can you name it?',
    '进入探索': 'Enter Exploration',
    '查看详情': 'View Details',
    '“万物有灵，历史不应只是冰冷的橱窗，而是一场活色生香的相遇。”': '"Everything has a spirit, and history should not be just a cold display case, but a vivid encounter."',
    '通过游戏可以更好地记住文物的特征和历史背景哦！': 'Playing games helps you remember artifact features and historical context better!',
    '精品文物': 'Exquisite Artifacts',
    'AI对话': 'AI Chat',
    '与文物互动': 'Interact with Artifacts',
    '互动游戏': 'Interactive Games',
    '趣味学习吴文化': 'Fun Learning of Wu Culture',
    '苏州博物馆艺术馆藏': 'Suzhou Museum Art Collection',
    '美学': 'The Aesthetic',
    '探索': 'Exploration',
    '馆藏': 'Collection',
    '智能': 'Intelligence',
    '互动': 'Interactive',
    '开启探索之旅': 'Begin your exploration journey',
    '沉浸式阅览馆藏珍品': 'Immersive viewing of museum collections',
    '进入库房': 'Enter the vault',
    '与跨越千年的文物对谈': 'Talk with millennia-crossing artifacts',
    '即刻启程': 'Start now',
    '趣味探寻吴地文明': 'Explore Wu civilization with fun',
    '吴地遗珍': 'Wu Treasures of Wu Region',
    '静默的历史回响': 'Silent Echoes of History',
    '中而新，苏而新': 'Chinese yet new, Suzhou yet new',
    '从五代的秘色瓷到明清的书画珍品，每一件文物都是吴地文化的碎片。我们在现代几何的光影中，跨越时空与古人对话。': 'From the secret-color porcelain of the Five Dynasties to the painting and calligraphy treasures of the Ming and Qing dynasties, each artifact is a fragment of Wu culture. In modern geometric light and shadow, we cross time to converse with the ancients.',
    '材质之美': 'Material Beauty',
    '涵盖青铜、玉石、陶瓷及丝绣，全方位展现古代工匠对自然材质的极致雕琢与审美。': 'Covering bronze, jade, ceramics, and silk embroidery, it fully showcases ancient craftsmen\'s exquisite workmanship and aesthetic refinement of natural materials.',
    '历史脉络': 'Historical Context',
    '从史前良渚文化到明清盛世，严谨梳理苏州两千五百年来的建城史与文脉传承。': 'From the prehistoric Liangzhu culture to the prosperous Ming and Qing eras, it carefully traces Suzhou\'s 2,500-year city-building history and cultural inheritance.',
    '深度交互': 'Deep Interaction',
    '利用AI导览与三维数字化技术，打破展柜的物理边界，近距离触摸文物的细节。': 'Using AI guided tours and 3D digitization technology to break the physical boundary of display cases and get close to artifact details.',
    '共收录 {count} 件珍贵文物': 'A total of {count} precious artifacts',
    '在游戏中学习吴文化知识': 'Learn Wu culture knowledge through games',
    '文物拼图': 'Artifact Puzzle',
    '将打乱的文物图片拼回完整': 'Put the scrambled artifact images back together',
    '猜猜文物': 'Guess the Artifact',
    '根据线索猜测文物名称': 'Guess the artifact name based on clues',
    '💡 提示：通过游戏可以更好地记住文物的特征和历史背景哦！': '💡 Tip: Games can help you better remember the characteristics and historical background of artifacts!',
    '文物不存在': 'Artifact does not exist',
    '返回文物列表': 'Return to artifacts list',
    '与TA对话': 'Chat with TA',
    '📷 图片': '📷 Image',
    '3D': '3D',
    '朝代': 'Dynasty',
    '年代': 'Year',
    '文物介绍': 'Artifact Introduction',
    '文物自述': 'Artifact Story',
    '得分: ': 'Score: ',
    ' / ': ' / ',
    '这是什么文物？': 'What artifact is this?',
    '🔍 显示线索 (3次)': '🔍 Show clue (3 times)',
    '🔍 再清晰一点 (2次)': '🔍 A bit clearer (2 times)',
    '🔍 最后一次提示 (1次)': '🔍 Final hint (1 time)',
    '✓ 已显示完整图片': '✓ Full image displayed',
    '💡 朝代：': '💡 Dynasty: ',
    '💡 年代：': '💡 Year: ',
    '💡 提示：': '💡 Hint: ',
    '🎉 回答正确！': '🎉 Correct answer!',
    '❌ 正确答案是：': '❌ Correct answer is: ',
    '游戏结束！': 'Game over!',
    '完美！你是文物专家！': 'Perfect! You are an artifact expert!',
    '不错！继续加油！': 'Good! Keep it up!',
    '多看看文物介绍吧~': 'Check out the artifact introductions more~',
    '文物修复计划': 'Artifact Restoration Plan',
    '正在修复': 'Restoring',
    '移动步数': 'Moves',
    '隐藏原图': 'Hide original',
    '查看原图': 'View original',
    '修复成功！': 'Restoration successful!',
    '你只用了 {moves} 步就让 {artifactName} 焕发新生。': 'You restored {artifactName} in just {moves} moves.',
    '你只用了 {moves} 次交换就让 {artifactName} 焕发新生。': 'You restored {artifactName} in just {moves} swaps.',
    '再玩一次': 'Play Again',
    '挑战下一关': 'Next challenge',
    '回到大厅': 'Back to lobby',
    '欢迎语前缀': '(adjusts clothes) Hello visitor, I am',
    '欢迎语中缀1': '. I have been in this museum showcase for a long time and feel quite lonely. Would you like to hear stories about the',
    '欢迎语中缀2': 'or learn about my origin?',
    '真珠舍利宝幢': 'Pearl Sarira Pagoda',
    '北宋': 'Northern Song Dynasty',
    '公元960-1127年': '960-1127 AD',
    '苏州博物馆镇馆之宝，是北宋时期的佛教圣物。宝幢通高122.6厘米，由木胎、金银、珍珠、宝石等材料制成，工艺精湛，是中国佛教文物中的珍品。': 'The treasure of Suzhou Museum, it is a Buddhist relic from the Northern Song Dynasty. The pagoda is 122.6 cm tall, made of wood, gold, silver, pearls, gemstones and other materials, with exquisite craftsmanship, and is a treasure among Chinese Buddhist cultural relics.',
    '我诞生于北宋太平兴国二年，是当时吴越国王钱俶为祈求国泰民安而建造的。历经千年风霜，我见证了苏州的兴衰变迁，承载着虔诚的信仰和精湛的工艺。每一颗珍珠、每一片金叶，都凝聚着古人的智慧与虔诚。': 'I was born in the second year of Taiping Xingguo in the Northern Song Dynasty, built by King Qian Chu of Wuyue to pray for national peace and prosperity. After thousands of years of wind and frost, I have witnessed the rise and fall of Suzhou, carrying devout faith and exquisite craftsmanship. Every pearl and every gold leaf embodies the wisdom and piety of the ancients.',
    '秘色瓷莲花碗': 'Secret Color Porcelain Lotus Bowl',
    '五代': 'Five Dynasties',
    '公元907-960年': '907-960 AD',
    '秘色瓷是越窑青瓷中的极品，专供皇室使用。这件莲花碗釉色青翠，造型优美，代表了五代时期制瓷工艺的最高水平。': 'Secret color porcelain is the finest of Yue kiln celadon, exclusively for the royal family. This lotus bowl has a jade-green glaze color and beautiful shape, representing the highest level of porcelain-making technology in the Five Dynasties period.',
    '我来自越窑，那个出产\'秘色瓷\'的神秘之地。我的釉色如千峰翠色，如湖水碧波。在五代十国的乱世中，我曾是王室贵胄的珍宝。如今静卧于苏州博物馆，继续诉说着千年前的繁华。': 'I come from Yue Kiln, the mysterious place that produces \'secret color porcelain\'. My glaze color is like the green of a thousand peaks, like the blue waves of a lake. In the chaotic times of the Five Dynasties and Ten Kingdoms, I was once a treasure of the royal nobility. Now I lie quietly in Suzhou Museum, continuing to tell the story of the prosperity a thousand years ago.',
    '吴王夫差剑': 'Sword of King Fuchai of Wu',
    '春秋': 'Spring and Autumn Period',
    '公元前473年': '473 BC',
    '吴王夫差剑是春秋时期吴国的青铜兵器，剑身修长，剑刃锋利，剑格镶嵌绿松石，剑身有清晰的铭文\'攻吴王夫差自作其元用\'。此剑代表了春秋时期吴越地区青铜铸造工艺的最高水平，是研究吴越历史和青铜文化的珍贵实物资料。': 'The Sword of King Fuchai is a bronze weapon from the Wu State during the Spring and Autumn Period. With a long blade, sharp edge, turquoise inlay on the guard, and clear inscription "Made by King Fuchai of Wu for his own use", this sword represents the highest level of bronze casting technology in the Wu-Yue region during the Spring and Autumn Period, and is a precious material for studying Wu-Yue history and bronze culture.',
    '我是吴王夫差的佩剑，见证了春秋末年吴越争霸的风云岁月。当年夫差持我南征北战，称霸一时。我曾饮过无数勇士的鲜血，也曾见证过吴越两国的兴衰荣辱。千年之后，我依然锋利如初，仿佛还能感受到当年金戈铁马的气息。': 'I am the personal sword of King Fuchai of Wu, witnessing the turbulent years of Wu-Yue rivalry at the end of the Spring and Autumn Period. In those days, Fuchai wielded me to conquer north and south, dominating the region for a time. I have tasted the blood of countless brave warriors and witnessed the rise and fall of both Wu and Yue states. After thousands of years, I remain as sharp as ever, as if still feeling the echoes of ancient battles.',
    '蟠螭三足提梁盉': 'Three-legged Bronze He with Coiled Chi Dragons',
    '战国': 'Warring States Period',
    '公元前475-221年': '475-221 BC',
    '蟠螭三足提梁盉是战国时期的青铜酒器，造型独特，器身装饰蟠螭纹，三足鼎立，提梁设计精巧。此器铸造工艺精湛，纹饰繁复精美，是战国时期青铜艺术的杰出代表，反映了当时高超的青铜铸造技术和审美水平。': 'The Three-legged Bronze He with Coiled Chi Dragons is a bronze wine vessel from the Warring States Period. Featuring a unique design with coiled chi dragon patterns on the body, three legs for stability, and an ingenious handle, this vessel showcases exquisite casting craftsmanship and intricate decorations. It is an outstanding representative of Warring States bronze art, reflecting the advanced bronze casting technology and aesthetic standards of the time.',
    '我是战国时期的青铜酒器，见证了那个百家争鸣、英雄辈出的时代。我的身上布满了精美的蟠螭纹饰，每一处都凝聚着工匠的心血。在战国的宴会上，我曾盛放过香醇的美酒，见证过无数次觥筹交错的场景。岁月流转，我依然保持着当年的威严与华美。': 'I am a bronze wine vessel from the Warring States Period, witnessing an era of great thinkers and heroes. My body is covered with exquisite coiled chi dragon patterns, each detail embodying the craftsman\'s painstaking effort. At the feasts of the Warring States, I have held fragrant wine and witnessed countless toasts. As time flows, I still maintain the dignity and magnificence of that era.',
    '随机推荐': 'Featured Archive',
    '换一批': 'Refresh',
    '搜索文物...': 'Search artifacts...',
    'FEATURED ARCHIVE': 'Featured Archive',
    'Dynasty': 'Dynasty',
    'EXQUISITE ARTIFACTS': 'Exquisite Artifacts',
    'SUZHOU MUSEUM DIGITAL COLLECTION': 'Suzhou Museum Digital Collection',
    'EXPLORE STORY': 'Explore Story',
    'View original': 'View original',
    '更多馆藏': 'More Collections',
    'Restoring': 'Restoring',
    'Moves': 'Moves',
    '交换次数': 'Swaps',
    '点击两个格子交换位置，将图片恢复原样': 'Click two tiles to swap positions and restore the image',
    'Show clue (3 times)': 'Show clue (3 times)',
    'A bit clearer (2 times)': 'A bit clearer (2 times)',
    'Final hint (1 time)': 'Final hint (1 time)',
    'Full image displayed': 'Full image displayed',
    'My Favorites': 'My Favorites',
    'Exploration Footprints': 'Exploration Footprints',
    'Log Out': 'Log Out',
    '数字馆员': 'Digital Curator',
    'My Achievements': 'My Achievements',
    '已解锁': 'Unlocked',
    '万物皆观': 'Master Curator',
    '已浏览全部文物': 'Viewed all artifacts',
  }
};

// 语言提供者组件
interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('zh');

  // 翻译函数
  const t = (key: string, variables?: Record<string, string | number>) => {
    let translation = translations[language][key as keyof typeof translations[typeof language]] || key;
    
    // 替换变量
    if (variables) {
      Object.entries(variables).forEach(([key, value]) => {
        // 同时支持单大括号和双大括号的变量格式
        translation = translation.replace(`{${key}}`, String(value));
        translation = translation.replace(`{{${key}}}`, String(value));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// 自定义钩子，用于在组件中使用语言上下文
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}